### ISSUE TITLE
exec /lando-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by remaxrickerts** [lando/core#195]
I updated my Lando version to latest to deal with a `docker-compose` issue (which turns out was just an alias problem) and now my MySQL 5.7 database fails to start with the error:
```
exec /lando-entrypoint.sh: exec format error
```
My install process:
```
updating lando
Generating plugin/cli update matrix... done [see table below]
✔ Updated @lando/core to v3.21.2


You are now up to date! with the latest and greatest!
adding /usr/local/bin to PATH
...
```
<img width="815" alt="DockerDesktop_InspectDB_PathEntrypoint" src="https://github.com/user-attachments/assets/375d979f-2ab8-4859-8b8e-c3ca8e6ffb45">

My last install was from Jan. 18, 2024. Is it possible to revert to this version and see if it works? I am running MacOS 14.6 and do not know if an update to my OS broke it.

I tried going back to the last packaged release: https://github.com/lando/lando/releases/tag/v3.20.8
but got this error output:
```
TypeError: Cannot read properties of undefined (reading 'buildEngine')
    at module.exports (/Users/rrickerts/.lando/plugins/@lando/core/tasks/setup.js:75:25)
    at /snapshot/cli/node_modules/@lando/core/lib/lando.js
From previous event:
    at process.processImmediate (node:internal/timers:471:21)
```

**Comment by remaxrickerts** [comment]
I fixed the startup issue by pulling a newer MySQL version:
```
  database:
    overrides:
      image: bitnami/mysql:5.7.43-debian-11-r73
```

**Comment by reynoldsalec** [comment]
Interesting that it was an issue. I just pushed out a new version of `lando/mysql` that updates the pinned versions of the `bitnami/mysql` images, so that should fix your particular issue.

Note that most of the recipes will need to update their version of `lando/mysql` to take advantage, so if you're having this issue using the workaround could still be necessary.

https://github.com/lando/mysql/issues/57
