### ISSUE TITLE
Can't install CA certificate on linux mint

### ISSUE THREAD

**Issue by beau-townsend** [lando/core#225]
When executing `lando rebuild`, I was prompted for a password to install a new CA certificate. After entering the password, I received the message that "linuxmint not supported! Could not locate package manager!." I am running Linux Mint 21.3 Cinnamon.
![image](https://github.com/user-attachments/assets/ed79e879-1e91-4916-ba6b-878d3ce91767)

How can I install the proper CA certificate? I'm not especially familiar with installing certificates, so I would appreciate as much instruction as you can provide.

Thanks!

**Comment by asantossmw** [comment]
On Manjaro Linux 24.1.1 using Docker version 27.2.1, build 9e34c9bb39

` ✖ Installing Lando Development Certificate Authority (CA)  FAILED`

Added the **--skip-install-ca** parameter it finishes the setup but when I try to start my app asked me again to install the Certificate and fails as on the setup

**Comment by asantossmw** [comment]
@beau-townsend I solved the issue temporarily on my local

Basically the process to copy the **LandoCA.crt** file needs to be added to the trusted certificates, on Arch Linux the way to do that is done executing the following commands on **Arch**:

Arch Linux uses **update-ca-trust** instead of **update-ca-certificates**. To install and update trusted certificates on Arch Linux, follow these steps:

Install update-ca-trust package: 

Run the command **sudo pacman -S update-ca-trust** to install the package.
Add the certificate: Place your certificate in the **/etc/ca-certificates/trust-source/anchors/** directory. The file name must end with .crt.

`cp -r ~/.lando/certs/LandoCA.crt /etc/ca-certificates/trust-source/anchors/`


Run **trust extract-compat**: Execute the command **sudo trust extract-compat** to update the trusted certificate store.

Verify the certificate: Check if the certificate has been successfully added by running **sudo update-ca-trust extract** and verifying the output.

After that i was able to complete the **lando setup** command

**lando setup -y**

lando setup is a hidden convenience command to help you satisify the
dependencies needed to run Lando. Typically it includes the installation and
setup of some combination of the below:

◼ Common Lando Plugins
◼ Docker Engine
◼ Docker Compose

However, if you already have the needed dependencies it will happily do nothing
and exit. It will attempt to install plugins first and then it will run any
needed setup tasks.

For more information on customizing setup please run lando setup --help
or visit https://docs.lando.dev/cli/setup.html

Generating plugin installation matrix... done [nothing to install]

Generating setup task installation matrix... done [nothing to install]

**As far as lando setup can tell you are good to go and do not require additional setup!**

As you are using linux-mint I think that you can figure out how to do this with apt and the update-ca-certificates toolkit!

**Comment by AaronFeledy** [comment]
@asantossmw Can you post `cat /etc/os-release`?

**Comment by beau-townsend** [comment]
I managed to bypass the issue by following the steps here for Debian: https://docs.lando.dev/core/v3/security.html

Interestingly, I'm still asked to accept the certificate from an unknown issuer despite having already set up my Firefox browser per the instructions on the page above, which was previously working (as in, not requiring me to accept the risk).

Thanks to all for the input and help!

**Comment by asantossmw** [comment]
Sorry I just see the last message from you. I pulled the latest update and works fine here. Thanks @AaronFeledy!

`cat /etc/os-release`

> NAME="Manjaro Linux"
> PRETTY_NAME="Manjaro Linux"
> ID=manjaro
> ID_LIKE=arch
> BUILD_ID=rolling
> ANSI_COLOR="32;1;24;144;200"
> HOME_URL="https://manjaro.org/"
> DOCUMENTATION_URL="https://wiki.manjaro.org/"
> SUPPORT_URL="https://forum.manjaro.org/"
> BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
> PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
> LOGO=manjarolinux

Have a great day!

**Comment by beau-townsend** [comment]
For anyone else facing the same issue, I wanted to provide a little more information.

In addition to the steps I mentioned above, I also had to import the Lando CA certificate into my browser in order to allow https connection. The following screen shots are from Firefox. On my system the cert is located under `~/<home folder>/.lando/certs`.

![image](https://github.com/user-attachments/assets/092d1168-e868-43f2-af1d-c098afc340da)
![image](https://github.com/user-attachments/assets/787fccca-36db-4cfe-93f5-75c53adfd092)
![image](https://github.com/user-attachments/assets/5bae350d-0b8a-43ec-9743-7516a149eb94)
