### ISSUE TITLE
Command "Installing Lando Development Certificate Authority (CA)"  hangs

### ISSUE THREAD

**Issue by githoober** [lando/core#297]
Recently, installing any recent version of Lando in WSL and running the Lando setup causes the installation attempt of the CA on the Windows Store to hang.

![image](https://github.com/user-attachments/assets/bf8db899-a5dd-4f7c-98dc-694216ae4f3b)

Running the command with the debug output is not helpful.

**Comment by pirog** [comment]
@githoober if you are running in WSL and do not have WSL Interoperability enabled then Lando will treat the environment as a `linux` environment. Based on your screenshot it looks like this is happening, which is not a problem, more a FYI.

That said, in order to install the certificate on Linux you should be prompted for your `sudo` password. So if you are not entering it at the prompt then that would explain the hang.

**Comment by githoober** [comment]
@pirog Thank you for your response. For some reason, the previous screenshot didn’t accurately reflect the issue I originally reported. I captured it after running `lando setup` a few times. However, a fresh install of Lando reveals the correct issue I must address: installing a CA to Windows Store hangs indefinitely (after providing the password).

![image](https://github.com/user-attachments/assets/e184dadf-8eff-4ffc-90d5-70d5433bafdb)

**Comment by pirog** [comment]
ok that screenshot makes more sense to me. 

when i do this in WSL i dont get a password prompt for the WIndows CA installation, rather, i get a popup detailing what is happening and a confirmation button which i need to press otherwise it will hang. im not sure if this is universal. can you provide more detail about what happens when it tries to install the CA on the Windows side?

**Comment by githoober** [comment]
@pirog I just realized I created this issue in lando/core instead of lando/lando-setup, as it seems more relevant to the setup scripts. Should we move the issue there?

Regarding the issue itself: I’ve confirmed that WSL interoperability is enabled:

![image](https://github.com/user-attachments/assets/044513cc-5634-43ac-97b6-6eb89530843b)

When I manually run the PowerShell script `install-system-ca-win32.ps1`, I get an appropriate error message after allowing it to _Run Once_:

![image](https://github.com/user-attachments/assets/3074bfc5-18d2-41a2-b97d-9c87b0eb24b1)

However, when I launch lando-setup, it just hangs. If any Windows popup is expected to show up at this point, it does not.

![image](https://github.com/user-attachments/assets/7d6b22e1-4c33-4121-963b-ee497e749d00)

**Comment by pirog** [comment]
@githoober i wouldnt expect the script to succeed if you run it manually without the correct options, mainly `-CA`.

My best guess is that Lando runs the script but like when you run it manually it asks you to choose how to deal with the security concern but you cannot provide a response so it hangs waiting. 

I think we will just have to explore how to deal with this use case better. In the meantime i'm guessing you can probably run the script manually using the options you see in the bottom of the screenshot you posted. Should be something like 

```powershell
~/.lando/scripts/install-system-ca-win32.ps1 -CA ~/.lando/certs/LandoCA.crt -Debug
```

@AaronFeledy it was my understanding that `-ExecutionPolicy Bypass` would prevent the prompt and thats how we are invoking the script from lando via `utils/run-powershell-script`. Can this be locked down by a sysadmin so a user cannot bypass on their own?

**Comment by pirog** [comment]
@githoober are you running in an environment where group policy forces the `ExecutionPolicy` to prompt/confirm as in the screenshot where you tried to run manually?

What happens if you try to manually set the execution policy? If this fails then maybe we can check for this first and if the user cannot bypass we can elevate and ask for admin credentials?

```powershell
Set-ExecutionPolicy -ExecutionPolicy Bypass
```

Note that this should not change the policy for your system, just for the running process.

**Comment by githoober** [comment]
@pirog Setting the execution policy manually in powershell indeed failes.

![image](https://github.com/user-attachments/assets/f18ba008-c73f-4cb4-8140-15e48e1a8022)


Also, I successfully ran the script that installs the CA in Windows Store yesterday inside powershell.exe. 
![image](https://github.com/user-attachments/assets/54fa98d2-0286-40ac-8df9-4502f0a2942e)

**Comment by pirog** [comment]
@githoober ok that narrows it down. 

i think we will need to assess whether regular users can run scripts unimpeded and if they cant im guessing we will need to prompt for admin credentials so they can.

**Comment by nikolas** [comment]
My lando install is hanging at this "Installing Lando Development Certificate Authority (CA)" step as well. I was prompted for my sudo password and I entered it. I am on Fedora Linux.
