### ISSUE TITLE
Lando on WSL tries to install Docker Desktop (since v3.23.21)

### ISSUE THREAD

**Issue by onetrev** [lando/core#308]
I updated to v3.23.21 yesterday and now oddly now all of a sudden Lando downloads and tries to install Docker Desktop whenver I rebuild / start. Upon checking [the docs](https://docs.lando.dev/install/wsl.html#wsl), it does seem like this is expected, but I hadn't seen this change noted anywhere in the changelogs. Did I miss it?

Moreover, what are the consequences for those already running Docker Engine on Linux? I'm reluctant to just install Docker Desktop over the top. Is there a key reason why this is now the default setup functionality? I don't want to remove WSL interoperability (which the docs list as the way to _avoid_ Docker Desktop install), so is there another way to prevent this? For now I can avoid this by hitting cancel each time the installer pops up, but that's not a long term solution. :)

**System Info:**
Lando v3.23.21
Linux style installation running in WSL2, thus Docker Engine on Linux is installed (I am not using Docker Desktop)

**Comment by pirog** [comment]
I think previously Lando was only checking to see if the `docker` CLI exists but now it does a stronger check which includes looking for `Docker Desktop.exe`. So, i'm guessing you were not getting the install prompt before because Lando was seeing `docker` from Docker Engine and was satisfied with that. 

It's the default functionality because Docker Desktop is the recommended way to install Docker in WSL and there is _considerable_ complexity trying to have it "just work" when the user could potentially have either or both Docker Desktop/Docker Engine installed. 

The "best" thing to do would probably be to uninstall docker engine in WSL and just install docker desktop and use that. If that is not a viable option you can try setting the below in your Lando global config.

```yaml
setup:
  buildEngine: false
```

i *think* this will skip the installer prompt issue but you may still experience weird behavior elsewhere because Lando will assume you are using Docker Desktop which you aren't. For example if you turn the Docker Engine daemon off in WSL Lando will try to launch Docker Desktop which will fail.

**Comment by onetrev** [comment]
Hey @pirog thank you so much for chasing this up. Hugely appreciated, you went above and beyond for this, thank you. 🥂

I went with _non-best_ option for now. It seemed safer since I have a few active projects. For anyone else looking in on this with the same issue, updating the Lando global config so far seems to be fine🤞.

**Comment by wwhurley** [comment]
I hope that in the future Lando can more readily support docker-ce under WSL. With systemd it works well and avoids problems with licensing of Docker Desktop.

**Comment by pirog** [comment]
it will and it will also support other backends. 

that said our current priority is to move everything over to Lando 4 which will make supporting different backends easier.

**Comment by Mgrmjp** [comment]
This seems to happen again.

**Comment by Mgrmjp** [comment]
It's already installed so it's weird it tries to set it up again. 🤷🏻‍♀️

**Comment by Lancelight** [comment]
Wow, what a pain. I had this problem too. It's to bad the lando install doesnt have enough brains in it to figure out that docker in the wsl2 instance is already set up and working and presents the user with a question of whether it should use native docker or install winblowz docker desktop (which is utterly horrendous, there are significant performance degradations when using docker desktop, especially when using Ollama + Local AI models, the performance drop with Docker Desktop is EXTREMELY noticeable when using local AI models or DL'ing items with a 2GBit connection inside the docker instance). I wish docker desktop would just die and never come back. It's garbage.
