### ISSUE TITLE
Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by GravlLift** [lando/core#75]
Versions v3.20.1 and higher (tested up to v3.20.4) and higher are completely unstartable on my Ubuntu WSL2 machine, resulting in the following output when any command is run (this output is from a simple `lando` command):

```
undefined:0


TypeError: Cannot read properties of null (reading 'id')
    at /snapshot/cli/node_modules/@lando/core/lib/bootstrap.js
    at /snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js
    at /snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js
    at baseForOwn (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at /snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js
    at baseMap (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at Function.map (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at interceptor (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at Function.thru (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at /snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js
```

v3.18.0 of lando still works for me, which claims to be using tag v3.16.0 of @lando/core. Checking the diff of changed lines between that tag and main, only two lines appear to attempt to access an `id` property, 282 and 286.

https://github.com/lando/core/blob/8dc2708857b9aaea4ca4f40efaf5cbfcc90b8ee3/lib/bootstrap.js#L281-L287

Looks like the culprit is likely line 286 not checking if `task` is an object before accessing its properties.

**Comment by pirog** [comment]
@GravlLift can you provide a Landofile for us to try and replicate with?

**Comment by cleverington** [comment]
Seeing the issue similarly on v3.21.8 using the `lagoon` recipe and the `nodebuilder` (for `uselagoon/node-14-builder`) fails to even let the `lando info` / `lando version` / `lando destroy` commands work.

**Comment by MacKinley** [comment]
Current Workaround for me: use Lando `3.23.13`.

------

I have this issue as well. Here was my setup:

- Ubuntu on WSL2: `24.04`
  - Systemd enabled
- Docker Engine on Ubuntu (NOT on Windows Host): `28.0.4`
- Lando: `3.24.3`
  - Installed via: `/bin/bash -c "$(curl -fsSL https://get.lando.dev/setup-lando.sh)"`

I downgraded Lando to `3.21.0` and was able to this setup working in my env.

I then installed and tested `3.21.2` which worked, followed by `3.22.3`. On installing `3.22.3` it also ran the following which did not happen when installing `3.24.3`:

``` bash
Generating setup task installation matrix... done [see table below]
[+] Running Setup Tasks 6/6
 ✔ Created Lando Development CA                                                Completed
 ✔ Installed Lando Development Certificate Authority (CA)                      Completed
 ✔ Installed orchestrator to /home/trudeaum/.lando/bin/docker-compose-v2.29.2  Completed
```

Then installed `3.23.13` which worked but got the following error when rebuilding:
``` bash
Pantheon pre-run scripting
/bin/sh: 1: /etc/lando/service/helpers/install-composer.sh: not found
```

Trying to install `3.23.14` and `3.23.26` resulted in errors.

Looks like Lando is trying to run specific code because it is aware that the Env in WSL on Windows but that code is breaking.
